language: generic
services:
  - docker

before_install:
  - docker build -t andystyles30/testdome-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true andystyles30/testdome-practice npm run test
  - docker run -e CI=true andystyles30/testdome-practice npm run lint

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-086089507028'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
