language: generic
services:
  - docker

before_install:
  - docker build -t andystyles30/testdome-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true andystyles30/testdome-practice npm run test
